name: Compile Arduino Sketch


on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install DFRobotDFPlayerMini
        run: |
            mkdir -p $HOME/Arduino/libraries
            git clone --depth 1 https://github.com/DFRobot/DFRobotDFPlayerMini.git
            mv DFRobotDFPlayerMini $HOME/Arduino/libraries/DFRobotDFPlayerMini

      - name: Compile Arduino sketch
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
          libraries: |
            -
